name: Deploy to gp-pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: Install yarn
      run: sudo apt-get update && sudo apt-get install yarn
    - name: Install project dependencies
      run: yarn install
    - name: Build
      run: yarn build
      env:
        REACT_APP_CURRENCY_API_KEY: ${{ secrets.CURRENCY_PUBLIC_API_KEY }}
    - name: Deploy to gh-pages
        if: success()
        uses: crazy-max/ghaction-github-pages@master
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
