name: CI Development flow

on:
  push:
    branches:    
      - develop
      - 'hotfix/*'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install yarn
        run: sudo apt-get update && sudo apt-get install yarn

      - uses: actions/checkout@v1
      - name: Install project dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn coverage
      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: ./reports/coverage
      - name: Analyze bundle size
        run: yarn analyze
      - uses: actions/upload-artifact@master
        with:
          name: build-reports
          path: ./reports/bundle-size.html

