name: CI flow

on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install yarn
        run: npm -g i yarn 
      - name: Install project dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Analyze bundle size
        run: yarn analyze
